apiVersion: v1
kind: Secret

metadata:
  name: wol-secret  # Name of the Secret resource 
  namespace: wol # Namespace where the Secret resides
  
type: Opaque  # Type of the Secret (Opaque means arbitrary data)

data:
  MAC: QjQtMkUtOTktQTMtRjItRDI= # Encoded data for the MAC address
  BROADCAST: MTkyLjE2OC44Ni4yNTU= # Encoded data for the broadcast address