# Persistent Volume Claim (PVC) configuration for Minecraft Server backup storage

apiVersion: v1
kind: PersistentVolumeClaim

metadata:
  # Metadata section for the PVC
  name: mc-backup-pvc # Name of the PersistentVolumeClaim
  namespace: mc-server  # Namespace where the PVC belongs

spec:
  # Specification section for the PVC

  # Access modes define how the volume can be mounted.
  accessModes:
    - ReadWriteOnce # Allows read and write access to a single node

  # Resources requested by the PVC
  resources:
    requests:
      storage: 5Gi  # Requesting 5 gigabytes of storage for the PVC