apiVersion: v1
kind: Pod
metadata:
  name: temp-pod
  namespace: mc-server
spec:
  containers:
  - name: temp-pod
    image: nginx:stable-alpine
    imagePullPolicy: IfNotPresent
    volumeMounts:
    - name: mc-vol
      mountPath: /data
    ports:
    - containerPort: 80
  volumes:
  - name: mc-vol
    persistentVolumeClaim:
      claimName: mc-pvc