apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-claim
  namespace: longhorn-test
spec:
  accessModes: 
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 2Gi
  