apiVersion: batch/v1
kind: CronJob
metadata: 
  name: porkbun-ddns-frequent
  namespace: porkbun-ddns
spec:
  schedule: "*/10 * * * *"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 300
      template:
        spec:
          restartPolicy: OnFailure
          containers:
            - name: ddns-updater
              image: cyrof/porkbun-ddns:latest
              imagePullPolicy: IfNotPresent
              envFrom:
                - secretRef:
                    name: porkbun-creds
