apiVersion: batch/v1
kind: CronJob
metadata:
  name: porkbun-ddns
  namespace: porkbun-ddns
spec:
  # run every day at 07:00 (SGT)
  schedule: "0 7 * * *"
  successfulJobsHistoryLimit: 10
  failedJobsHistoryLimit: 10

  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 604800
      template:
        spec:
          restartPolicy: OnFailure
          containers:
            - name: ddns-updater
              image: cyrof/porkbun-ddns:latest
              imagePullPolicy: IfNotPresent
              envFrom:
                - secretRef:
                    name: porkbun-creds
