apiVersion: v1
kind: Secret

metadata: 
  name: knfolio-secrets
  namespace: folio

type: Opaque 
stringData: 
  EMAIL_USER: "aHMuYXV0by5ub3JlcGx5QGdtYWlsLmNvbQ=="
  EMAIL_PASS: "eXhld2pqaGdtdGF6emtocg=="
  RECIPIENT_EMAIL: "a2VpdGhuZW8wMEBnbWFpbC5jb20="