---
- name: Check Raspberry pi OS version and architecture
  hosts: all
  gather_facts: true
  become: false

  tasks:
      - name: Show OS release info
        ansible.builtin.command: cat /etc/os-release
        register: os_release
        changed_when: false

      - name: Show kernel version
        ansible.builtin.command: uname -r
        register: kernel_version
        changed_when: false

      - name: Show CPU architecture
        ansible.builtin.command: uname -m
        register: arch
        changed_when: false

      - name: Show userspace bitness
        ansible.builtin.command: getconf LONG_BIT
        register: bitness
        changed_when: false

      - name: Display Raspberry Pi system summary
        ansible.builtin.debug:
            msg:
                - 'Host: {{ inventory_hostname }}'
                - 'OS: {{ ansible_distribution }} {{ ansible_distribution_version }}'
                - 'OS Release: '
                - '{{ os_release.stdout_lines }}'
                - 'Kernel: {{ kernel_version.stdout }}'
                - 'Architecture: {{ arch.stdout }}'
                - 'Userspace: {{ bitness.stdout }}-bit'
