---
- name: Get k3s join info from master
  hosts: k3s_master
  become: true
  gather_facts: false

  tasks:
    - name: Read k3s node-token
      ansible.builtin.slurp:
        src: /var/lib/rancher/k3s/server/node-token
      register: node_token_b64

    - name: Get master LAN IP
      ansible.builtin.shell: "hostname -I | awk '{print $1}'"
      register: master_ip
      changed_when: false

    - name: Set join facts
      ansible.builtin.set_fact:
        k3s_master_url: "https://{{ master_ip.stdout }}:6443"
        k3s_node_token: "{{ node_token_b64.content | b64decode | trim }}"

- name: Install k3s agent and join cluster
  hosts: new_nodes
  become: true
  gather_facts: false

  tasks:
    - name: Install prerequisites
      ansible.builtin.apt:
        update_cache: true
        name:
          - curl
          - ca-certificates
          - iptables
          - socat
          - conntrack
        state: present

    - name: Install k3s agent (pinned version)
      ansible.builtin.shell: |
        set -eu
        curl -sfL https://get.k3s.io | \
          INSTALL_K3S_VERSION="v1.32.3+k3s1" \
          K3S_URL="{{ hostvars[groups['k3s_master'][0]].k3s_master_url }}" \
          K3S_TOKEN="{{ hostvars[groups['k3s_master'][0]].k3s_node_token }}" \
          sh -s - agent
      args:
        creates: /usr/local/bin/k3s

    - name: Enable and start k3s-agent
      ansible.builtin.systemd:
        name: k3s-agent
        enabled: true
        state: started

    - name: Wait for k3s-agent to become active
      ansible.builtin.command: systemctl is-active k3s-agent
      register: agent_state
      retries: 10
      delay: 3
      until: agent_state.stdout.strip() == "active"
      changed_when: false
