# Ansible playbook to update and upgrade all apt packages on the system and reboots if necessary

- hosts: all
  become: true
  tasks:
      # Update the apt package cache
      - name: Update apt packages
        apt:
            update_cache: true

      # Perform a dist-upgrade and remove unnecessary packages
      - name: Upgrade all apt packages
        apt:
            upgrade: dist
            autoremove: true

      # Reboot the system if required
      - name: Reboot if needed
        reboot:
            reboot_timeout: 300 # Maximun wait time for system to reboot (in seconds)

