apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata: 
  name: letsencrypt-http01
  namespace: cert-manager
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: keithneo00@gmail.com
    privateKeySecretRef:
      name: letsencrypt-http01-account-key

    solvers:
      - http01: 
          ingress:
            class: nginx 
